/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_data_free(a: number): void;
export function data_new(a: number): number;
export function data_update_year(a: number, b: number): void;
export function data_get_full_years(a: number): number;
export function data_get_geral(a: number): number;
export function data_get_post(a: number): number;
export function data_get_post_imagem(a: number): number;
export function data_get_post_musica(a: number): number;
export function data_get_post_texto(a: number): number;
export function data_get_post_video(a: number): number;
export function data_get_post_24(a: number): number;
export function data_get_day_geral(a: number): number;
export function data_get_day_post(a: number): number;
export function data_get_day_post_imagem(a: number): number;
export function data_get_day_post_musica(a: number): number;
export function data_get_day_post_texto(a: number): number;
export function data_get_day_post_video(a: number): number;
export function data_get_day_post_24(a: number): number;
export function data_get_soma(a: number): number;
export function data_teste(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function data_init(a: number, b: number, c: number, d: number, e: number): void;
export function data_update(a: number, b: number): void;
export function __wbg_canvas_free(a: number): void;
export function canvas_new(a: number, b: number): number;
export function canvas_resize(a: number, b: number, c: number, d: number): void;
export function canvas_init(a: number, b: number, c: number, d: number, e: number): void;
export function canvas_update(a: number, b: number): void;
export function canvas_mouseover(a: number, b: number, c: number): void;
export function canvas_mouseout(a: number): void;
export function canvas_draw_lines(a: number, b: number, c: number, d: number, e: number): void;
export function fetch_ipv6(): number;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hb8d01335e4c885bd(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h4a812093c680470c(a: number, b: number, c: number, d: number): void;
